comunica-sparql-link-traversal-solid --idp https://wiser-solid-xi.interactions.ics.unisg.ch/\
  "PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?person
WHERE {
  <https://wiser-solid-xi.interactions.ics.unisg.ch/kai/profile/card#me> (foaf:knows|^foaf:knows)+ ?person.
}" --lenient